import { BiPageTemplate, type BiPageCopyMap } from "@/components/pages/bi-page-template";

const OFFICIAL_URL = "https://www.getdbt.com/";

const copyByLocale: BiPageCopyMap = {
  zh: {
    badge: "开源 · dbt",
    title: "dbt：分析工程与 SQL 建模",
    subtitle: "SQL 转换、宏与测试、文档与治理，兼容仓库与 Lakehouse",
    description:
      "dbt（data build tool）是开源的分析工程框架，使用 SQL 定义模型与依赖，支持宏/Jinja、物化策略、种子数据、数据测试与文档生成，可在云仓或 Lakehouse 上构建可维护的语义层与转换管道。",
    highlights: [
      { title: "SQL 即代码", description: "用 SQL + Jinja 定义模型、依赖与宏，支持增量/表/视图等物化。" },
      { title: "测试与文档", description: "内置/自定义测试、Schema YAML、自动生成文档与血缘。" },
      { title: "环境与工作流", description: "本地 CLI、自托管、dbt Cloud，支持 CI/CD、预览与权限。" },
      { title: "生态集成", description: "兼容主流仓库/Lakehouse 与 BI/编排器（如 Airflow、Dagster、Prefect）。" },
    ],
    useCases: [
      "在仓库上构建可维护的转换层",
      "指标/维度/事实的语义建模",
      "数据质量测试与文档化",
      "与编排/BI 集成的分析工程工作流",
    ],
    ctaVisit: "访问 dbt",
    ctaBack: "返回首页",
  },
  en: {
    badge: "Open source · dbt",
    title: "dbt: analytics engineering with SQL",
    subtitle: "SQL transformations, macros/tests, docs, and governance for warehouses/Lakehouse",
    description:
      "dbt (data build tool) is an open-source analytics engineering framework that uses SQL to define models and dependencies. It supports macros/Jinja, materializations, seeds, data tests, and autogenerated docs, building maintainable semantic layers and transformations on warehouses or Lakehouse.",
    highlights: [
      { title: "SQL as code", description: "Define models, dependencies, and macros in SQL + Jinja with table/view/incremental materializations." },
      { title: "Tests & docs", description: "Built-in/custom tests, schema YAML, autogenerated docs and lineage." },
      { title: "Environments & workflows", description: "CLI/self-hosted/dbt Cloud with CI/CD, previews, and permissions." },
      { title: "Ecosystem integrations", description: "Works with major warehouses/Lakehouse and orchestrators/BI (Airflow, Dagster, Prefect)." },
    ],
    useCases: [
      "Maintainable transformation layer on warehouses",
      "Semantic modeling for metrics/dimensions/facts",
      "Data quality testing and documentation",
      "Analytics engineering workflows with orchestration/BI",
    ],
    ctaVisit: "Visit dbt",
    ctaBack: "Back to home",
  },
};

export function DbtPageContent({ locale }: { locale?: string }) {
  return <BiPageTemplate copyByLocale={copyByLocale} locale={locale} officialUrl={OFFICIAL_URL} />;
}
